core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

food_tracker/urls.py
from django.urls import path
from . import views

app_name = 'food_tracker'

urlpatterns = [
    path('log', views.food_log, name='food_log'),

    path('search/', views.search_food, name='search_food'),
    path('add/<int:fdc_id>', views.add_food_entry, name='add_food_entry'),
    path('entry_detail/<int:pk>', views.entry_detail, name='entry_detail'),

    path('delete/<int:pk>/', views.delete_food_entry, name='delete_food_entry'),
    path('calculate_tdee/', views.calculate_tdee, name='calculate_tdee'),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('delete/<int:pk>', views.delete_log, name='delete_log'),

    path('set_goal/', views.set_goal, name='set_goal'),
    path('goal_detail/<int:pk>', views.goal_detail, name='goal_detail'),
    path('goal/<int:pk>/delete', views.delete_goal, name='delete_goal'),
    path('goal/<int:pk>/update', views.update_goal, name='update_goal'),

    path('weight-data/', views.weight_data, name='weight_data'),
    path('weight-chart/', views.weight_chart, name='weight_chart'),

    path('log_bmi/', views.log_bmi, name='log_bmi'),
    path('bmi/<int:pk>', views.bmi_detail, name='bmi_detail'),

    path('weight_logs/', views.weight_logs, name='weight_logs'), 
]

weight_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('', include('core.urls')),
    path('tracker/', include('tracker.urls')),
    path('food_tracker/', include('food_tracker.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')    

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

core/views.py
from django.shortcuts import render, redirect

from tracker.models import WeightLog, Goal, BMILog

from .forms import SignupForm

# Render the index
def index(request):
    return render(request, 'core/index.html')

# Render weight tracker page
# def weight_tracker(request):
#     logs = WeightLog.objects.filter(created_by=request.user).order_by('-date', '-id')
#     goal = Goal.objects.filter(created_by=request.user).last() # get the latest goal
#     bmi_logs = BMILog.objects.filter(created_by=request.user)

#     latest_log = None
#     if logs:
#         latest_log = logs.first().weight
    
#     return render(request, 'core/weight_tracker.html', {
#         'goal': goal,
#         'latest_log': latest_log,
#         'logs': logs,
#         'bmi_logs': bmi_logs,
#         })

# Handle user sign up
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form,
    })

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %}{% endblock %} | Tracker</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Tracker</a> 

        <div class="space-x-6">
            <!-- <a href="{% url 'tracker:new' %}" class="text-lg font-semibold hover:text-gray-500">Log New Weight</a>
            <a href="{% url 'tracker:set_goal' %}" class="text-lg font-semibold hover:text-gray-500">Set Goal</a>
            <a href="{% url 'tracker:log_bmi' %}" class="text-lg font-semibold hover:text-gray-500">Calculate BMI</a>
            <a href="{% url 'food_tracker:search_food' %}" class="text-lg font-semibold hover:text-gray-500">Search Food</a>
            <a href="{% url 'food_tracker:calculate_tdee' %}" class="text-lg font-semibold hover:text-gray-500" title="Total Daily Energy Expenditure">TDEE</a> -->
            <a href="/" class="text-lg font-semibold hover:text-gray-500">Home</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">About</a>

            {% if request.user.is_authenticated %}
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        {% block content %}
        {% endblock %}
    </nav>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container mx-auto mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="text-2xl mb-6">Choose Your Service</h1>
    <div class="grid grid-cols-2 gap-6">
        <a href="./tracker" class="block bg-blue-500 hover:bg-blue-700 text-white text-center py-4 px-8 rounded-xl">Weight Tracking</a>
        <a href="{% url 'food_tracker:food_log' %}" class="block bg-green-500 hover:bg-green-500 text-white text-center py-4 px-8 rounded-xl">Food Intake</a>
    </div>
</div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Log In</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign Up</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Repeat Password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

core/templates/core/weight_tracker.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <!-- <div class="fixed bottom-4 right-4">
            <a href="{% url 'tracker:new' %}" class="=bg-green-500 text-white p-4 rounded-full shadow-lg hover:bg-green-700">
                <span class="text-2xl">+</span>
            </a>
        </div> -->
        <a href="{% url 'tracker:new' %}" class="inline-block bg-blue-500 text-white font-semibold px-4 py-2 rounded-xl shadow-lg hover:bg-blue-700 mr-2" title="Add Log">+</a>
        {% if not logs %} 
            <p class="text-2xl"><strong>You don't have any weight logs!</strong></p>
        {% else %}
        <a href="{% url 'tracker:weight_logs' %}" class="bg-blue-500 text-white px-4 py-2 rounded-xl mt-4 inline-block hover:bg-blue-700 shadow-lg">Logs</a>
            {% include 'tracker/weight_chart.html' %}
        {% endif %}
    </div>

    <!-- <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        {% if not goal %} 
            <p class="text-2xl"><strong>You don't have any goal set yet!</strong></p>
        {% else %}
        <a href="{% url 'tracker:goal_detail' goal.id %}">
            <h2 class="mb-12 text-2xl text-center">Your Weight Goal</h2>

            {% if latest_log <= goal.target_weight and goal.goal_type == 'weight_loss' %} 
                <h2 class="text-2xl"><strong>You have reached your goal!</strong></h2>
                <p>Goal: <strong>{{ goal.get_goal_type_display }} lbs</strong></p>
                <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>

                {% if latest_log is not None %}
                <p>Current Weight: <strong>{{ latest_log }} lbs</strong></p>
                {% endif %}

                <p>Target Weight: <strong>{{ goal.target_weight }} lbs</strong></p>

                <a href="{% url 'tracker:update_goal' goal.id %}" class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Update Goal</a>
                <a href="{% url 'tracker:delete_goal' goal.id%}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Delete Goal</a>
            {% elif latest_log >= goal.target_weight and goal.goal_type == 'weight_gain' %} 
                <h2 class="text-2xl"><strong>You have reached your goal!</strong></h2>
                <p>Goal: <strong>{{ goal.get_goal_type_display }}</strong></p>
                <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>

                {% if latest_log is not None %}
                <p>Current Weight: <strong>{{ latest_log }} lbs</strong></p>
                {% endif %}

                <p>Target Weight: <strong>{{ goal.target_weight }} lbs</strong></p>
                <a href="{% url 'tracker:set_goal' %}" class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Set New Goal</a>
                <a href="{% url 'tracker:delete_goal' goal.id%}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Delete Goal</a>
            {% else %}
                {% if goal %}
                    <p>Goal: <strong>{{ goal.get_goal_type_display }}</strong></p>
                    <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>

                    {% if latest_log is not None %}
                    <p>Current Weight: <strong>{{ latest_log }} lbs</strong></p>
                    {% endif %}

                    <p>Goal Weight: <strong>{{ goal.target_weight}} lbs</strong></p>
                    <p>Target Date: <strong>{{ goal.target_date }}</strong></p>
                {% endif %}
            {% endif %}
        {% endif %}
        </a>
    </div> -->

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        {% include 'tracker/goal.html' with current_weight=latest_log %}
    </div>

    <!-- <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <div class="grid gap-3">
            <h2 class="text-2xl">BMI Logs</h2>
            {% if not bmi_logs %}
                <p class="text-2xl"><strong>You don't have any BMI logs!</strong></p>
            {% else %}
                {% for bmi_log in bmi_logs %}
                    <a href="{% url 'tracker:bmi_detail' bmi_log.id %}">
                        <div class="p-6 bg-white rounded-xl">
                            <p class="text-gray-500"><strong>{{ bmi_log.interpret_bmi }}!</strong></p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div> -->
{% endblock %}