core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

food_tracker/urls.py
from django.urls import path
from . import views

app_name = 'food_tracker'

urlpatterns = [
    path('log', views.food_log, name='food_log'),

    path('search/', views.search_food, name='search_food'),
    path('add/<int:fdc_id>', views.add_food_entry, name='add_food_entry'),
    path('entry_detail/<int:pk>', views.entry_detail, name='entry_detail'),

    path('delete/<int:pk>/', views.delete_food_entry, name='delete_food_entry'),
    path('calculate_tdee/', views.calculate_tdee, name='calculate_tdee'),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('delete/<int:pk>', views.delete_log, name='delete_log'),

    path('set_goal/', views.set_goal, name='set_goal'),
    path('goal_detail/<int:pk>', views.goal_detail, name='goal_detail'),
    path('goal/<int:pk>/delete', views.delete_goal, name='delete_goal'),
    path('goal/<int:pk>/update', views.update_goal, name='update_goal'),

    path('weight-data/', views.weight_data, name='weight_data'),
    path('weight-chart/', views.weight_chart, name='weight_chart'),

    path('log_bmi/', views.log_bmi, name='log_bmi'),
    path('bmi/<int:pk>', views.bmi_detail, name='bmi_detail'),

    path('weight_logs/', views.weight_logs, name='weight_logs'), 
]

weight_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('', include('core.urls')),
    path('tracker/', include('tracker.urls')),
    path('food_tracker/', include('food_tracker.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class WeightLog(models.Model):
    created_by = models.ForeignKey(User, related_name='weights', on_delete=models.CASCADE)
    weight = models.FloatField()
    date = models.DateField()
    image = models.ImageField(upload_to='progress_images', blank=True, null=True)
    
    def __str__(self):
        return f'{self.created_by} - {self.weight} lbs'
    
class Goal(models.Model):
    GOAL_CHOICES = [
        ('weight_loss', 'Weight Loss'),
        ('weight_gain', 'Weight Gain'),
        ('maintenance', 'Maintenance'),
    ]
    WEEKLY_GOAL = [
        ('lose_1', 'Lose 1 pound per week'),
        ('lose_2', 'Lose 2 pounds per week'),
        ('gain_1', 'Gain 1 pound per week'),
        ('gain_2', 'Gain 2 pounds per week')
    ]
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    goal_type = models.CharField(max_length=20, choices=GOAL_CHOICES)
    weekly_goal = models.CharField(max_length=50, choices=WEEKLY_GOAL)
    target_weight = models.FloatField()
    start_weight = models.FloatField()
    target_date = models.DateField(blank=True, null=True)

    def get_goal_type_display(self):
        return dict(self.GOAL_CHOICES).get(self.goal_type, 'Unknown')
    
    def get_weekly_goal_display(self):
        return dict(self.WEEKLY_GOAL).get(self.weekly_goal, 'Unknown')
    
    def __str__(self):
        return f'{self.created_by} - {self.goal_type} - {self.target_weight} lbs'

    def progress_percentage(self):
        if self.goal_type == 'weight_loss':
            total_weight_to_lose = self.start_weight - self.target_weight
            weight_lost = self.start_weight - self.created_by.weights.latest('date').weight
            return round((weight_lost / total_weight_to_lose) * 100, 2)
        elif self.goal_type == 'weight_gain':
            total_weight_to_gain = self.target_weight - self.start_weight
            weight_gained = self.created_by.weights.latest('date').weight - self.start_weight
            return round((weight_gained / total_weight_to_gain) * 100, 2)
        return 0 # maintain

class BMILog(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bmi_logs')
    date = models.DateField(blank=True, null=True)
    weight = models.FloatField() # in pounds
    height = models.FloatField() # in inches

    def calculate_bmi(self):
        # add a feature later to convert input in feet to inches
        return round((self.weight / (self.height ** 2)) * 703, 2)

    def interpret_bmi(self):
        bmi = self.calculate_bmi()
        if bmi < 18.5:
            return 'Underweight'
        elif bmi < 24.9:
            return 'Healthy Weight'
        elif bmi < 29.9:
            return 'Overweight'
        else:
            return 'Obese'
    
    def __str__(self):
        return f'{self.created_by} - {self.date} - BMI: {self.calculate_bmi():.2f}'

tracker/forms.py
from django import forms

from .models import WeightLog, Goal, BMILog

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewWeightLogForm(forms.ModelForm):
    class Meta:
        model = WeightLog
        fields = ('weight', 'date', 'image', )
    
        widgets = {
            'weight': forms.TextInput(attrs={
                'placeholder': 'Enter weight in lbs',
                'class': INPUT_CLASSES,
            }), 
            'date': forms.DateInput(attrs={
                'type': 'date',
                'placeholder': 'Enter date',
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            })
        }

class EditWeightLogForm(forms.ModelForm):
    class Meta:
        model = WeightLog
        fields = ('weight', 'image', )
    
        widgets = {
            'weight': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }), 
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
            })
        }

class SetGoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ('goal_type', 'weekly_goal', 'start_weight', 'target_weight',)

        widgets = {
            'goal_type': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'weekly_goal': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'start_weight': forms.TextInput(attrs={
                'placeholder': 'Enter weight in lbs',
                'class': INPUT_CLASSES,
            }),
            'target_weight': forms.TextInput(attrs={
                'placeholder': 'Enter weight in lbs',
                'class': INPUT_CLASSES,
            }),
            # 'target_date': forms.DateInput(attrs={
            #     'type': 'date',
            #     'class': INPUT_CLASSES,
            # })
        }

class HeightField(forms.MultiValueField):
    def __init__(self, *args, **kwargs):
        fields = (
            forms.IntegerField(min_value=0, label='Feet'),
            forms.IntegerField(min_value=0, label='Inches'),
        )
        super().__init__(fields, *args, **kwargs)
    
    def compress(self, data_list):
        if data_list:
            feet = data_list[0]
            inches = data_list[1]
            total_inches = (feet * 12) + inches
            return total_inches
        return None
    
class HeightWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = [
            forms.NumberInput(attrs={
                'placeholder': 'Feet',
                'class': 'border rounded-xl px-4 py-2 w-24',
                'min': 0,
                'max': 8,
            }),
            forms.NumberInput(attrs={
                'placeholder': 'Inches',
                'class': 'border rounded-xl px-4 py-2 w-24', 
                'min': 0,
                'max': 11,
            }),
        ]
        super().__init__(widgets, attrs)

    def decompress(self, value):
        if value: 
            feet = value // 12
            inches = value % 12
            return [feet, inches]
        return [0, 0]

class BMILogForm(forms.ModelForm):
    height = HeightField(widget=HeightWidget())

    class Meta:
        model = BMILog
        fields = ('weight', 'height', )
        widgets = {
            # 'date': forms.DateInput(attrs={
            #     'type': 'date',
            #     'class': INPUT_CLASSES
            # }),
            'weight': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
            }),
        }

tracker/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse

from .forms import NewWeightLogForm, SetGoalForm, BMILogForm
from .models import WeightLog, Goal, BMILog

# Render index page of weight tracker app
@login_required
def index(request):
    logs = WeightLog.objects.filter(created_by=request.user).order_by('-date', '-id')
    goal = Goal.objects.filter(created_by=request.user).last() # get the latest goal
    bmi_logs = BMILog.objects.filter(created_by=request.user)

    latest_log = None
    if logs:
        latest_log = logs.first().weight
    
    return render(request, 'tracker/index.html', {
        'goal': goal,
        'latest_log': latest_log,
        'logs': logs,
        'bmi_logs': bmi_logs,
        })

# All weight logs
@login_required
def weight_logs(request):
    logs = WeightLog.objects.filter(created_by=request.user).order_by('date')
    latest_log = None
    if logs:
        latest_log = logs.first().weight
    
    return render(request, 'tracker/weight_logs.html', {
        'logs': logs,
        'latest_log': latest_log,
    })

# Goal detail
@login_required
def goal_detail(request, pk):
    goal = get_object_or_404(Goal, pk=pk)
    try:
        current_weight = goal.created_by.weights.latest('date').weight
    except WeightLog.DoesNotExist:
        current_weight = None

    return render(request, 'tracker/goal.html', {
        'current_weight': current_weight,
        'goal': goal,
    })

# Log new weight
@login_required
def new(request):
    if request.method == 'POST':
        form = NewWeightLogForm(request.POST, request.FILES)

        if form.is_valid():
            weight_log = form.save(commit=False)
            weight_log.created_by = request.user
            weight_log.save()

            return redirect('tracker:index')
    else:
        form = NewWeightLogForm()

    return render(request, 'tracker/form.html', {
        'form': form,
        'title': 'New Weight Log',
    })

# Set new goal
@login_required
def set_goal(request):
    if request.method == 'POST':
        form = SetGoalForm(request.POST)

        if form.is_valid():
            goal = form.save(commit=False)
            goal.created_by = request.user
            goal.save()

            return redirect('tracker:index')
    else:
        form = SetGoalForm()

    return render(request, 'tracker/form.html', {
        'form': form,
        'title': 'Set Goal',
    })

# Update goal
@login_required
def update_goal(request, pk):
    goal = get_object_or_404(Goal, pk=pk)
    if request.method == 'POST':
        form = SetGoalForm(request.POST, instance=goal)

        if form.is_valid():
            form.save()
            return redirect('tracker:index')
    else:
        form = SetGoalForm(instance=goal)
    return render(request, 'tracker/update_goal.html', {
        'form': form,
        'goal': goal,
    })

# Delete weight log
@login_required
def delete_log(request, pk):
    log = get_object_or_404(WeightLog, pk=pk, created_by=request.user)
    log.delete()

    return redirect('tracker:weight_logs')

# Delete goal
@login_required
def delete_goal(request, pk):
    goal = get_object_or_404(Goal, pk=pk, created_by=request.user)
    goal.delete()

    return redirect('tracker:index')

# Weight Trends Chart
@login_required
def weight_data(request):
    weight_logs = WeightLog.objects.filter(created_by=request.user).order_by('date')
    goal = Goal.objects.filter(created_by=request.user).first() # Assuming one goal per user
    target_weight = goal.target_weight if goal else None

    data = {
        'dates': [log.date.strftime('%Y-%m-%d') for log in weight_logs],
        'weights': [log.weight for log in weight_logs],
        'target_weight': target_weight,
    }
    return JsonResponse(data)

@login_required
def weight_chart(request):
    return render(request, 'tracker/weight_chart.html')


# BMI Tracker
@login_required
def log_bmi(request):
    if request.method == 'POST':
        form = BMILogForm(request.POST)
        if form.is_valid():
            bmi_log = form.save(commit=False)
            bmi_log.created_by = request.user
            bmi_log.save()
            return redirect('tracker:bmi_detail', pk=bmi_log.pk)
    else:
        form = BMILogForm()
    return render(request, 'tracker/log_bmi.html', {
        'form': form,
    })

# BMI detail
@login_required
def bmi_detail(request, pk):
    bmi_log = BMILog.objects.get(pk=pk, created_by=request.user)
    bmi = bmi_log.calculate_bmi()
    status = bmi_log.interpret_bmi()

    feet, inches = divmod(bmi_log.height, 12)
    height = f"{int(feet)}'{int(inches)}"
    return render(request, 'tracker/bmi_detail.html', {
        'bmi_log': bmi_log, 
        'bmi': bmi,
        'height': height,
        'status': status,
    })

tracker/templates/tracker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %}{% endblock %} | Weight Tracker</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/tracker" class="text-xl font-semibold">Weight Tracker</a> 

        <div class="space-x-6">
            <div class="border inline-block px-2 py-2 m-2 bg-blue-500 hover:bg-blue-700 rounded-xl shadow-lg">
                <a href="{% url 'food_tracker:food_log' %}" class="text-lg font-semibold">Food Tracker</a>
            </div>
            <a href="{% url 'tracker:new' %}" class="text-lg font-semibold hover:text-gray-500">Log New Weight</a>
            <a href="{% url 'tracker:set_goal' %}" class="text-lg font-semibold hover:text-gray-500">Set Goal</a>
            <a href="{% url 'tracker:log_bmi' %}" class="text-lg font-semibold hover:text-gray-500">Calculate BMI</a>
            <!-- <a href="{% url 'food_tracker:search_food' %}" class="text-lg font-semibold hover:text-gray-500">Search Food</a>
            <a href="{% url 'food_tracker:calculate_tdee' %}" class="text-lg font-semibold hover:text-gray-500" title="Total Daily Energy Expenditure">TDEE</a> -->
            

            <!-- {% if request.user.is_authenticated %}
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %} -->
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

tracker/templates/tracker/goal.html
{% if goal %}
    <h1 class="text-2xl mb-6">{{ goal.get_goal_type_display }}</h1>
    <p>Target Weight: <strong>{{ goal.target_weight }} lbs</strong></p>
    {% if current_weight %}
        <p>Current Weight: <strong>{{ current_weight }} lbs</strong></p>
    {% endif %}
    <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>
    <p>Target Date: <strong>{{ goal.target_date }}</strong></p>

    {% if current_weight %}
        {% if goal.goal_type == 'weight_loss' and current_weight <= goal.target_weight %}
            <div class="bg-green-100 p-4 rounded-xl mt-6">
                <h2 class="text-xl font-semibold">Congratulations! You have reached your goal!</h2>
                <p>Would you like to set a new goal?</p>
                <a href="{% url 'tracker:set_goal' %}" class="bg-blue-500 text-white px-4 py-2 rounded mt-4 inline-block">Set New Goal</a>
            </div>
        {% elif goal.goal_type == 'weight_gain' and current_weight >= goal.target_weight %}
        <div class="bg-green-100 p-4 rounded-xl mt-6">
            <h2 class="text-xl font-semibold">Congratulations! You have reached your goal!</h2>
            <p>Would you like to set a new goal?</p>
            <a href="{% url 'tracker:set_goal' %}" class="bg-blue-500 text-white px-4 py-2 rounded mt-4 inline-block">Set New Goal</a>
        </div>
        {% else %}
            <div class="progress-bar-container mt-6 bg-gray-500">
                <div class="progress-bar bg-blue-400" style="width: {{ goal.progress_percentage }}%;"></div>
            </div>
            <p>{{ goal.progress_percentage }}% completed</p>
            <a href="{% url 'tracker:update_goal' goal.id %}" class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-xl mt-4 mr-4 inline-block shadow-lg">Update Goal</a>
        {% endif %}
    {% endif %}

<a href="{% url 'tracker:delete_goal' goal.id %}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-xl mt-4 inline-block shadow-lg">Delete Goal</a>
{% else %}
    <p class="text-2xl mb-6">No goal set!</p>
    <a href="{% url 'tracker:set_goal' %}" class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Set New Goal</a>
{% endif %}

tracker/templates/tracker/index.html
{% extends 'tracker/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <!-- <div class="fixed bottom-4 right-4">
            <a href="{% url 'tracker:new' %}" class="=bg-green-500 text-white p-4 rounded-full shadow-lg hover:bg-green-700">
                <span class="text-2xl">+</span>
            </a>
        </div> -->
        <a href="{% url 'tracker:new' %}" class="inline-block bg-blue-500 text-white font-semibold px-4 py-2 rounded-xl shadow-lg hover:bg-blue-700 mr-2" title="Add Log">+</a>
        {% if not logs %} 
            <p class="text-2xl"><strong>You don't have any weight logs!</strong></p>
        {% else %}
        <a href="{% url 'tracker:weight_logs' %}" class="bg-blue-500 text-white px-4 py-2 rounded-xl mt-4 inline-block hover:bg-blue-700 shadow-lg">Logs</a>
            {% include 'tracker/weight_chart.html' %}
        {% endif %}
    </div>

    <!-- <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        {% if not goal %} 
            <p class="text-2xl"><strong>You don't have any goal set yet!</strong></p>
        {% else %}
        <a href="{% url 'tracker:goal_detail' goal.id %}">
            <h2 class="mb-12 text-2xl text-center">Your Weight Goal</h2>

            {% if latest_log <= goal.target_weight and goal.goal_type == 'weight_loss' %} 
                <h2 class="text-2xl"><strong>You have reached your goal!</strong></h2>
                <p>Goal: <strong>{{ goal.get_goal_type_display }} lbs</strong></p>
                <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>

                {% if latest_log is not None %}
                <p>Current Weight: <strong>{{ latest_log }} lbs</strong></p>
                {% endif %}

                <p>Target Weight: <strong>{{ goal.target_weight }} lbs</strong></p>

                <a href="{% url 'tracker:update_goal' goal.id %}" class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Update Goal</a>
                <a href="{% url 'tracker:delete_goal' goal.id%}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Delete Goal</a>
            {% elif latest_log >= goal.target_weight and goal.goal_type == 'weight_gain' %} 
                <h2 class="text-2xl"><strong>You have reached your goal!</strong></h2>
                <p>Goal: <strong>{{ goal.get_goal_type_display }}</strong></p>
                <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>

                {% if latest_log is not None %}
                <p>Current Weight: <strong>{{ latest_log }} lbs</strong></p>
                {% endif %}

                <p>Target Weight: <strong>{{ goal.target_weight }} lbs</strong></p>
                <a href="{% url 'tracker:set_goal' %}" class="bg-blue-500 hover:bg-blue-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Set New Goal</a>
                <a href="{% url 'tracker:delete_goal' goal.id%}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-xl mt-4 inline-block">Delete Goal</a>
            {% else %}
                {% if goal %}
                    <p>Goal: <strong>{{ goal.get_goal_type_display }}</strong></p>
                    <p>Start Weight: <strong>{{ goal.start_weight }} lbs</strong></p>

                    {% if latest_log is not None %}
                    <p>Current Weight: <strong>{{ latest_log }} lbs</strong></p>
                    {% endif %}

                    <p>Goal Weight: <strong>{{ goal.target_weight}} lbs</strong></p>
                    <p>Target Date: <strong>{{ goal.target_date }}</strong></p>
                {% endif %}
            {% endif %}
        {% endif %}
        </a>
    </div> -->

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        {% include 'tracker/goal.html' with current_weight=latest_log %}
    </div>

    <!-- <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <div class="grid gap-3">
            <h2 class="text-2xl">BMI Logs</h2>
            {% if not bmi_logs %}
                <p class="text-2xl"><strong>You don't have any BMI logs!</strong></p>
            {% else %}
                {% for bmi_log in bmi_logs %}
                    <a href="{% url 'tracker:bmi_detail' bmi_log.id %}">
                        <div class="p-6 bg-white rounded-xl">
                            <p class="text-gray-500"><strong>{{ bmi_log.interpret_bmi }}!</strong></p>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
        </div>
    </div> -->
{% endblock %}

tracker/templates/tracker/log_bmi.html
{% extends 'tracker/base.html' %}

{% block title %}Log BMI{% endblock %}

{% block content %}
<form method="post" action="{% url 'tracker:log_bmi' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %} 
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Save</button>
</form>
{% endblock %}

tracker/templates/tracker/weight_chart.html
<div class="container mx-auto mt-6 px-6 py-2 bg-gray-100 rounded-xl">
    <h1 class="text-2xl mb-6">Weight Trends</h1>
    <canvas id="weightChart" width="400" height="160"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        fetch("{% url 'tracker:weight_data' %}")
            .then(response => response.json())
            .then(data => {
                const ctx = document.getElementById('weightChart').getContext('2d');
                const targetWeight = data.target_weight;

                // Calculate min and max values for y-axis
                const weights = data.weights;
                const maxWeight = Math.max(...weights);
                const minWeight = Math.min(...weights);
                const range = 10;

                const minY = minWeight < targetWeight ? minWeight - range : targetWeight - range;
                const maxY = maxWeight > targetWeight ? maxWeight + range : targetWeight + range;

                const annotations = {};
                if (targetWeight !== null && targetWeight !== undefined) {
                    annotations.line1 = {
                        type: 'line',
                        yMin: targetWeight,
                        yMax: targetWeight,
                        borderColor: 'rgba(255, 99, 132, 1)',
                        borderWidth: 2,
                        label: {
                            content: 'Target Weight',
                            enabled: true,
                            position: 'end',
                            backgroundColor: 'rgba(255, 99, 132, 0.8)',
                            color: 'white',
                            font: {
                                size: 12,
                                weight: 'bold',
                            },
                            padding: {
                                top: 4,
                                bottom: 4,
                                left: 8, 
                                right: 8,
                            }
                        }
                    };
                }

                const weightChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: data.dates,
                        datasets: [{
                            label: 'Weight',
                            data: data.weights,
                            borderColor: 'rgba(75, 192, 192, 1)',
                            backgroundColor: 'rgba(75, 192, 192, 0.2)',
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            x: {
                                type: 'time',
                                time: {
                                    unit: 'day'
                                }
                            },
                            y: {
                                beginAtZero: false,
                                min: minY,
                                max: maxY,
                            },
                        },
                        plugins: {
                            annotation: {
                                annotations: annotations,
                            },
                            tooltip: {
                                enabled: true,
                                backgroundColor: 'rgba(0, 0, 0, 0.8)', // background color of the tooltip
                                titleFont: {
                                    size: 14, // font size of the title
                                    weight: 'bold', // font weight of the title
                                    family: 'Arial', // font family of the title
                                    style: 'italic', // font style of the title
                                    lineHeight: 1.2 // line height of the title
                                },
                                titleColor: '#ffffff', // color of the title text
                                bodyFont: {
                                    size: 12, // font size of the body text
                                    family: 'Arial', // font family of the body text
                                    style: 'normal', // font style of the body text
                                    lineHeight: 1.2, // line height of the body text
                                },
                                bodyColor: '#ffffff', // Color of the body text
                                borderColor: 'rgba(255, 99, 132, 1)', // Border color of the tooltip
                                borderWidth: 1, // Border width of the tooltip
                                padding: 10, // Padding inside the tooltip
                                callbacks: {
                                    label: function(context) {
                                        let label = context.dataset.label || '';
                                        if (label) {
                                            label += ': ';
                                        }
                                        if (context.parsed.y != null) {
                                            label += context.parsed.y + ' lbs';
                                        }
                                        return label;
                                    }
                                }
                            },
                            legend: {
                                display: true,
                                position: 'top',
                                labels: {
                                    font: {
                                        size: 12, 
                                        family: 'Arial',
                                        weight: 'bold',
                                        style: 'normal'
                                    },
                                    color: '#000000'
                                },
                            }
                        }
                    }
                });
            });
    });
</script>