core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login')
]

food_tracker/urls.py
from django.urls import path
from . import views

app_name = 'food_tracker'

urlpatterns = [
    path('log', views.food_log, name='food_log'),

    path('search/', views.search_food, name='search_food'),
    path('add/<int:fdc_id>', views.add_food_entry, name='add_food_entry'),
    path('entry_detail/<int:pk>', views.entry_detail, name='entry_detail'),

    path('delete/<int:pk>/', views.delete_food_entry, name='delete_food_entry'),
    path('calculate_tdee/', views.calculate_tdee, name='calculate_tdee'),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('delete/<int:pk>', views.delete_log, name='delete_log'),

    path('set_goal/', views.set_goal, name='set_goal'),
    path('goal_detail/<int:pk>', views.goal_detail, name='goal_detail'),
    path('goal/<int:pk>/delete', views.delete_goal, name='delete_goal'),
    path('goal/<int:pk>/update', views.update_goal, name='update_goal'),

    path('weight-data/', views.weight_data, name='weight_data'),
    path('weight-chart/', views.weight_chart, name='weight_chart'),

    path('log_bmi/', views.log_bmi, name='log_bmi'),
    path('bmi/<int:pk>', views.bmi_detail, name='bmi_detail'),

    path('weight_logs/', views.weight_logs, name='weight_logs'), 
]

weight_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('', include('core.urls')),
    path('tracker/', include('tracker.urls')),
    path('food_tracker/', include('food_tracker.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_tracker/models.py
from django.db import models
from django.contrib.auth.models import User

class FoodEntry(models.Model):
    MEAL_TYPE_CHOICES = [
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
        ('snacks', 'Snacks'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food_name = models.CharField(max_length=255)
    calories = models.FloatField()
    protein = models.FloatField()
    fat = models.FloatField()
    carbs = models.FloatField()
    date = models.DateField(auto_now_add=True)
    meal_type = models.CharField(max_length=10, choices=MEAL_TYPE_CHOICES, default='breakfast')
    servings = models.FloatField(default=1)

    class Meta: 
        verbose_name_plural = 'Food Entries'

    def __str__(self):
        return f'{self.food_name} - {self.calories} kcal'
    
class CalculateTDEE(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]

    ACTIVITY_LEVEL_CHOICES = [
        (1.2, 'Sedentary (little or no exercise)'),
        (1.375, 'Lightly active (light exercise/sports 1-3 days/week)'),
        (1.55, 'Moderately active (moderate exercise/sports 3-5 days/week)'),
        (1.725, 'Very active (hard exercise/sports 6-7 days a week)'),
        (1.9, 'Super active (very hard exercise/sports & physical job)'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    age = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    weight = models.FloatField() # in lbs
    height = models.FloatField() # in in
    activity_level = models.FloatField(choices=ACTIVITY_LEVEL_CHOICES)

    def calculate_bmr(self):
        if self.gender == 'M':
            return 10 * (self.weight * 0.453592) + 6.25 * (self.height * 2.54) - 5 * self.age + 5
        else:
            return 10 * (self.weight * 0.453592) + 6.25 * (self.height * 2.54) - 5 * self.age - 161
    
    def calculate_tdee(self):
        bmr = self.calculate_bmr()
        return round(bmr * self.activity_level)
    
    def __str__(self):
        return f'{self.user.username} - TDEE: {self.calculate_tdee()}'

food_tracker/forms.py
from django import forms
from .models import CalculateTDEE

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class FoodSearchForm(forms.Form):
    query = forms.CharField(
        label='Search for food', 
        max_length=255, 
        widget=forms.TextInput(attrs={'class': 'py-4 px-6 rounded-xl border'})
    )

class HeightField(forms.MultiValueField):
    def __init__(self, *args, **kwargs):
        fields = (
            forms.IntegerField(min_value=0, label='Feet'),
            forms.IntegerField(min_value=0, label='Inches'),
        )
        super().__init__(fields, *args, **kwargs)
    
    def compress(self, data_list):
        if data_list:
            feet = data_list[0]
            inches = data_list[1]
            total_inches = (feet * 12) + inches
            return total_inches
        return None
    
class HeightWidget(forms.MultiWidget):
    def __init__(self, attrs=None):
        widgets = [
            forms.NumberInput(attrs={
                'placeholder': 'Feet',
                'class': 'border rounded-xl px-4 py-2 w-24',
                'min': 0,
                'max': 8,
            }),
            forms.NumberInput(attrs={
                'placeholder': 'Inches',
                'class': 'border rounded-xl px-4 py-2 w-24', 
                'min': 0,
                'max': 11,
            }),
        ]
        super().__init__(widgets, attrs)

    def decompress(self, value):
        if value: 
            feet = value // 12
            inches = value % 12
            return [feet, inches]
        return [0, 0]

class CalculateTDEEForm(forms.ModelForm):
    height = HeightField(widget=HeightWidget())
    
    class Meta:
        model = CalculateTDEE
        fields = ('age', 'gender', 'weight', 'height', 'activity_level', )
        widgets = {
            'age': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'gender': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            'weight': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'activity_level': forms.Select(attrs={
                'class': INPUT_CLASSES,
            }),
            
        }

food_tracker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import FoodSearchForm, CalculateTDEEForm    
from .models import FoodEntry, CalculateTDEE

from tracker.models import Goal # Import Goal model from tracker

from datetime import date
import requests

# Search for food
@login_required
def search_food(request):
    if request.method == 'POST':
        form = FoodSearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            url = f'https://api.nal.usda.gov/fdc/v1/foods/search?api_key={settings.USDA_API_KEY}&query={query}'
            response = requests.get(url)
            data = response.json()
            return render(request, 'food_tracker/search_results.html', {
                'data': data,
            })
    else:
        form = FoodSearchForm()
    return render(request, 'food_tracker/search_food.html', {
        'form': form,
    })

# Add food entry
@login_required
def add_food_entry(request, fdc_id):
    url = f'https://api.nal.usda.gov/fdc/v1/food/{fdc_id}?api_key={settings.USDA_API_KEY}'
    response = requests.get(url)
    data = response.json()
    food_name = data['description']
    nutrients = {nutrient['nutrient'].get('name', ''): (nutrient.get('amount', 0), nutrient['nutrient'].get('unitName', '')) for nutrient in data['foodNutrients']}

    protein, protein_unit = nutrients.get('Protein', (0, ''))
    fat, fat_unit = nutrients.get('Total lipid (fat)', (0, ''))
    carbs, carbs_unit = nutrients.get('Carbohydrate, by difference', (0, ''))

    # Ensure unit of calories is kcal
    calories = 0
    for nutrient in data.get('foodNutrients', []):
        if nutrient is None:
            continue
        if ('Energy' in nutrient['nutrient']['name']) and ('kcal' in nutrient['nutrient']['unitName']):
            calories = nutrient.get('amount', 0)
            break
    
    if request.method == 'POST':
        meal_type = request.POST.get('meal_type')
        servings = float(request.POST.get('servings', 1))

        FoodEntry.objects.create(
            user=request.user,
            food_name=food_name,
            calories=calories * servings,
            protein=protein * servings,
            fat=fat * servings,
            carbs=carbs * servings,
            meal_type=meal_type,
            servings=servings
        )
        return redirect('food_tracker:food_log')
    
    return render(request, 'food_tracker/add_food_entry.html', {
        'food_name': food_name,
        'calories': calories,
        'protein': protein,
        'fat': fat,
        'carbs': carbs,
    })

# Render the index page of the food logging app
@login_required
def food_log(request):
    today = date.today()
    meal_type = request.GET.get('meal_type', 'all')
    if meal_type == 'all':
        entries = FoodEntry.objects.filter(user=request.user, date=today).order_by('-date')
    else:
        entries = FoodEntry.objects.filter(user=request.user, date=today, meal_type=meal_type).order_by('-date')

    # All entries
    all_entries = FoodEntry.objects.filter(user=request.user, date=today).order_by('-date')

    # Calculate TDEE
    tdee_calculate = CalculateTDEE.objects.filter(user=request.user).last()
    tdee = tdee_calculate.calculate_tdee()
    recommended_calories = tdee

    # Total amount for each macro
    total_calories = sum(entry.calories for entry in all_entries)
    total_protein = sum(entry.protein for entry in all_entries)
    total_fat = sum(entry.fat for entry in all_entries)
    total_carbs = sum(entry.carbs for entry in all_entries)

    weekly_goal = 'Not set!'

    # Fetch the user's goal
    goals = Goal.objects.filter(created_by=request.user)
    if goals.exists():
        goal = goals.first()
        weekly_goal = goal.get_weekly_goal_display()
        if goal.goal_type == 'weight_loss':
            if goal.weekly_goal == 'lose_1':
                recommended_calories = tdee - 500 # Create a 500 calorie deficit
            elif goal.weekly_goal == 'lose_2':
                recommended_calories = tdee - 1000 # Create a 1000 calorie deficit
        elif goal.goal_type == 'weight_gain':
            if goal.weekly_goal == 'gain_3':
                recommended_calories = tdee + 500
            elif goal.weekly_goal == 'gain_4':
                recommended_calories = tdee + 1000
        else:
            recommended_calories = tdee # Maintenance
    else:
        recommended_calories = tdee # Default to maintenance if no goals are found
    
    calories_left = recommended_calories - total_calories
    # Calculate calories over
    calories_over = 0
    if calories_left < 0:
        calories_over = -calories_left

    # Calculate the percentage of calories consumed
    if recommended_calories > 0:
        calories_percentage = (total_calories / recommended_calories) * 100
    else:
        calories_percentage = 0

    # Meals
    meals = ['breakfast', 'lunch', 'dinner', 'snacks']

    return render(request, 'food_tracker/food_log.html', {
        'entries': entries,
        'tdee': tdee,
        'calories_left': round(calories_left),
        'recommended_calories': recommended_calories,
        'weekly_goal': weekly_goal,
        'calories_over': round(calories_over),
        'total_calories': round(total_calories),
        'total_protein': round(total_protein),
        'total_fat': round(total_fat),
        'total_carbs': round(total_carbs),
        'meal_type': meal_type,
        'calories_percentage': calories_percentage,
        'meals': meals,
    })

@login_required
def entry_detail(request, pk):
    entry = get_object_or_404(FoodEntry, pk=pk, user=request.user)

    return render(request, 'food_tracker/entry_detail.html', {
        'food_name': entry.food_name,
        'calories': entry.calories,
        'protein': entry.protein,
        'fat': entry.fat,
        'carbs': entry.carbs,
        'servings': entry.servings,
    })

@login_required
def calculate_tdee(request):
    if request.method == 'POST':
        form = CalculateTDEEForm(request.POST)
        if form.is_valid():
            tdee = form.save(commit=False)
            tdee.user = request.user
            tdee.save()
            return redirect('food_tracker:food_log')
    else:
        form = CalculateTDEEForm()
    return render(request, 'food_tracker/calculate_tdee.html', {
        'form': form,
    })

@login_required
def delete_food_entry(request, pk):
    food_entry = get_object_or_404(FoodEntry, pk=pk, user=request.user)
    food_entry.delete()
    return redirect('food_tracker:food_log')

food_tracker/templates/food_tracker/add_food_entry.html
{% extends 'food_tracker/base.html' %}

{% block title %}Add Food Entry{% endblock %}

{% block content %}

<div class="container mx-auto mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="text-2xl mb-6 font-semibold">Add Food Entry</h1>
    <form method="post">
        {% csrf_token %}
        <p>Food Name: <strong>{{ food_name }}</strong></p>
        <p>Calories: <strong>{{ calories }} cal</strong></p>
        <p>Protein: <strong>{{ protein }} g</strong></p>
        <p>Fat: <strong>{{ fat }} g</strong></p>
        <p>Carbs: <strong>{{ carbs }} g</strong></p>

        <label for="servings_{{ food.fdcId }}">Servings:</label>
        <input type="number" name="servings" id="servings_{{ food.fdcId }}" min="1" value="1" required class="border rounded-xl px-2 py-1 mb-1">
        <br>
        <label for="meal_type">Meal Type:</label>
        <select name="meal_type" id="meal_type" required class="border rounded-xl px-2 py-1">
            <option value="breakfast">Breakfast</option>
            <option value="lunch">Lunch</option>
            <option value="dinner">Dinner</option>
            <option value="snacks">Snacks</option>
        </select>
        <br>
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded-xl mt-4 shadow-lg">+</button>
    </form>
</div>

{% endblock %}

food_tracker/templates/food_tracker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %}{% endblock %} | Food Tracker</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="{% url 'food_tracker:food_log' %}" class="text-xl font-semibold">Food Tracker</a> 

        <div class="space-x-6">
            <div class="border inline-block px-2 py-2 m-2 bg-blue-500 hover:bg-blue-700 rounded-xl shadow-lg">
                <a href="/tracker" class="text-lg font-semibold">Weight Tracker</a>
            </div>
            <!-- <a href="{% url 'tracker:new' %}" class="text-lg font-semibold hover:text-gray-500">Log New Weight</a>
            <a href="{% url 'tracker:set_goal' %}" class="text-lg font-semibold hover:text-gray-500">Set Goal</a>
            <a href="{% url 'tracker:log_bmi' %}" class="text-lg font-semibold hover:text-gray-500">Calculate BMI</a> -->
            <a href="{% url 'food_tracker:search_food' %}" class="text-lg font-semibold hover:text-gray-500">Search Food</a>
            <a href="{% url 'food_tracker:calculate_tdee' %}" class="text-lg font-semibold hover:text-gray-500" title="Total Daily Energy Expenditure">Total Daily Energy Expenditure</a>
            

            <!-- {% if request.user.is_authenticated %}
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %} -->
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

food_tracker/templates/food_tracker/calculate_tdee.html
{% extends 'food_tracker/base.html' %}

{% block title %}Calculate TDEE{% endblock %}

{% block content %}
<form method="post" action="{% url 'food_tracker:calculate_tdee' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %} 
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Save</button>
</form>
{% endblock %}

food_tracker/templates/food_tracker/entry_detail.html
{% extends 'food_tracker/base.html' %}

{% block title %}Entry Detail{% endblock %}

{% block content %}

<div class="container mx-auto mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="text-2xl font-semibold">{{ food_name }}</h2>
    <p class="text-xl mt-3">Number of servings: {{ servings }}</p>
    <table class="table-auto w-1/2 m-6">
        <thead>
            <tr>
                <th class="px-4 py-2">Macro</th>
                <th class="px-4 py-2">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="border px-4 py-2">Calories</td>
                <td class="border px-4 py-2">{{ calories }} cal</td>
            </tr>
            <tr>
                <td class="border px-4 py-2">Protein</td>
                <td class="border px-4 py-2">{{ protein }} g</td>
            </tr>
            <tr>
                <td class="border px-4 py-2">Carbohydrates</td>
                <td class="border px-4 py-2">{{ carbs }} g</td>
            </tr>
            <tr>
                <td class="border px-4 py-2">Fat</td>
                <td class="border px-4 py-2">{{ fat }} g</td>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

food_tracker/templates/food_tracker/food_log.html
{% extends 'food_tracker/base.html' %}

{% block title %}Food Log{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Food Logs</h2>
    <p class="text-xl m-6">Goal: <span class="font-semibold">{{ weekly_goal }}</span></p>
    <p class="text-xl m-6">Recommended Daily Calories: <span class="font-semibold">{{ recommended_calories }} cal</span></p>
    <p class="text-xl m-6">Calories Today: <span class="font-semibold">{{ total_calories }} cal</span></p>

    {% if calories_left >= 0 %}
    <p class="text-xl m-6">Calories Left : <span class="font-semibold">{{ calories_left }} cal</span></p>
    {% else %}
    <p class="text-xl m-6">Calories Over: <span class="font-semibold">{{ calories_over }} cal</span></p>
    {% endif %}

    <table class="table-auto w-1/2 m-6">
        <thead>
            <tr>
                <th class="px-4 py-2">Macro</th>
                <th class="px-4 py-2">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="border px-4 py-2">Protein</td>
                <td class="border px-4 py-2">{{ total_protein }} g</td>
            </tr>
            <tr>
                <td class="border px-4 py-2">Carbohydrates</td>
                <td class="border px-4 py-2">{{ total_carbs }} g</td>
            </tr>
            <tr>
                <td class="border px-4 py-2">Fat</td>
                <td class="border px-4 py-2">{{ total_fat }} g</td>
            </tr>
        </tbody>
    </table>

    <div class="progress-circle-container">
        <div class="progress-circle" id="progress-circle">
            <div class="progress-text" id="progress-text">
                {{ total_calories }} / {{ recommended_calories }} cal
            </div>
        </div>
    </div>
    
    {% for meal in meals %}
        <p class="text-2xl font-semibold"> {{ meal|title }}</p>
        {% if entries is not Empty %}
        <div class="mt-6 mb-4">
            <table class="min-w-full bg-white">
                <thead>
                    <tr>
                        <th class="py-2">Food Name</th>
                        <th class="py-2">Calories</th>
                        <th class="py-2">Servings</th>
                        <th class="py-2">Protein (g)</th>
                        <th class="py-2">Fat (g)</th>
                        <th class="py-2">Carbs (g)</th>
                        <th class="py-2">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entry in entries %}
                        {% if entry.meal_type == meal %}
                            <tr>
                                <td class="border px-4 py-2">
                                    <a href="{%url 'food_tracker:entry_detail' entry.pk %}">
                                        {{ entry.food_name }}
                                    </a>
                                </td>
                                <td class="border px-4 py-2 text-center">{{ entry.calories }}</td>
                                <td class="border px-4 py-2 text-center">{{ entry.servings }}</td>
                                <td class="border px-4 py-2 text-center">{{ entry.protein }}</td>
                                <td class="border px-4 py-2 text-center">{{ entry.fat }}</td>
                                <td class="border px-4 py-2 text-center">{{ entry.carbs }}</td>
                                <td class="border px-4 py-2 text-center">
                                    <a href="{% url 'food_tracker:delete_food_entry' entry.pk %}" class="bg-red-500 hover:bg-red-700 text-white px-4 py-2 rounded-xl">Delete</a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    {% endfor %}

    <a href="{% url 'food_tracker:search_food' %}" class="bg-blue-500 hover:bg-blue-700 px-4 py-2 text-white rounded-xl">Search Food</a>
</div>

<style>
    .progress-circle-container {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-bottom: 20px;
    }

    .progress-circle {
        width: 200px;
        height: 200px;
        border-radius: 50%;
        background: conic-gradient(
            rgb(59 130 246) {{ calories_percentage }}%,
            #e0e0e0 {{ calories_percentage }}%   
        );
        display: flex;
        justify-content: center;
        align-items: center;
        position: relative;
        box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
    }

    .progress-circle::before {
        content: '';
        width: 170px;
        height: 170px;
        border-radius: 50%;
        background: rgb(243 244 246);
        position: absolute;
    }

    .progress-text {
        position: absolute;
        font-size: 18px;
        font-weight: bold;
        color: #333;
    }

</style>
{% endblock %}

food_tracker/templates/food_tracker/search_food.html
{% extends 'food_tracker/base.html' %}

{% block title %}Search Food{% endblock %}

{% block content %}
<form method="post">
    <!-- <h1 class="mb-6 text-3xl">Search for Food</h1> -->
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="mt-4 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 text-white rounded-xl">Search</button>

</form>
{% endblock %}

food_tracker/templates/food_tracker/search_results.html
{% extends 'food_tracker/base.html' %}

{% block title %}Seach Results{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <a href="{% url 'food_tracker:search_food' %}" class="bg-blue-500 hover:bg-blue-700 text-white mt-4 py-4 px-8 text-lg rounded-xl">Search Food</a>
    <h2 class="mb-12 text-2xl text-center">Search Results</h1>

    <div class="grid gap-3">
        {% for food in data.foods %}
            <div class="p-6 bg-white rounded-xl">
                <div class="inline-block mr-10">
                    <a href="{% url 'food_tracker:add_food_entry' food.fdcId %}">
                        <p class="text-2xl">{{ food.description }}</p>
                    </a>

                    {% for nutrient in food.foodNutrients %}
                        {% if nutrient.nutrientName == 'Energy' and nutrient.unitName == 'KCAL' %}
                            <p class="text-gray-500">{{ nutrient.value }} cal</p>
                        {% endif %}
                    {% endfor %}
                </div>
                <form method="post" action="{% url 'food_tracker:add_food_entry' food.fdcId %}">
                    {% csrf_token %}
                    <label for="servings_{{ food.fdcId }}">Servings:</label>
                    <input type="number" name="servings" id="servings_{{ food.fdcId }}" min="1" value="1" required class="border rounded-xl px-2 py-1">
                    <br>
                    <label for="meal_type">Meal Type:</label>
                    <select name="meal_type" id="meal_type_{{ food.fdcId }}" required class="border rounded-xl px-2 py-1">
                        <option value="breakfast">Breakfast</option>
                        <option value="lunch">Lunch</option>
                        <option value="dinner">Dinner</option>
                        <option value="snacks">Snacks</option>
                    </select>
                    <button type="submit" class="inline-block bg-blue-500 text-white font-semibold px-4 py-2 rounded-xl hover:bg-blue-700" title="Add Food">+</button>
                </form>
                <!-- <a href="{% url 'food_tracker:add_food_entry' food.fdcId %}" class="inline-block bg-blue-500 text-white font-semibold px-4 py-2 rounded-xl hover:bg-blue-700" title="Add Food">+</a> -->
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}